import type { SbpPhoneCountryId } from '@/lib/sbp/sbpPhoneCountries';

export type ForeignSbpCountryId = Exclude<SbpPhoneCountryId, 'RU'>;

/** Банки-партнёры трансграничного СБП (получатель в стране назначения). */
export const FOREIGN_SBP_BANKS: Record<ForeignSbpCountryId, readonly string[]> = {
  BY: [
    'Беларусбанк',
    'Приорбанк',
    'Белагропромбанк',
    'Белинвестбанк',
    'Белгазпромбанк',
    'БПС-Сбербанк',
    'Технобанк',
    'БТА Банк',
    'Паритетбанк',
    'БНБ-Банк',
    'БелВЭБ',
    'МТБанк',
    'Идея Банк',
    'РРБ-Банк',
    'Альфа-Банк Беларусь',
  ],
  KZ: [
    'Kaspi Bank',
    'Народный Банк Казахстана',
    'Bereke Bank',
    'ForteBank',
    'Банк ЦентрКредит',
    'Jusan Bank',
    'Eurasian Bank',
    'Home Credit Bank',
    'Freedom Bank Kazakhstan',
    'Bank RBK',
    'Altyn Bank',
    'Nurbank',
    'Bank Freedom Finance Kazakhstan',
    'Ситибанк Казахстан',
  ],
  UZ: [
    'Kapitalbank',
    'Hamkorbank',
    'Ipoteka Bank',
    'Agrobank',
    'Asakabank',
    'Trustbank',
    'Aloqabank',
    'Turonbank',
    'Universal Bank',
    'Uzpromstroybank',
    'InfinBANK',
    'Davr Bank',
    'Trastbank',
    'Asia Alliance Bank',
    'Poytaxt Bank',
  ],
  KG: [
    'MBank',
    'Optima Bank',
    'Bakai Bank',
    'Demir Bank',
    'KICB',
    'RSK Bank',
    'Keremet Bank',
    'Aiyl Bank',
    'Bank of Asia',
    'FINCA Bank',
    'Kompanion Bank',
    'Eldik Bank',
  ],
  TJ: [
    'Амонатбонк',
    'Эсхата Банк',
    'Ориёнбонк',
    'Алиф Банк',
    'Спитамен Банк',
    'Хумо Банк',
    'МДО Матин',
    'МДО Имони Интернешнл',
    'МДО Хумо',
    'МДО Финка',
    'Тавхидбонк',
  ],
  AM: [
    'Ameriabank',
    'Ardshinbank',
    'ACBA Bank',
    'Inecobank',
    'IDBank',
    'Converse Bank',
    'Araratbank',
    'Armswissbank',
    'Evocabank',
    'Unibank',
    'Byblos Bank Armenia',
    'VTB Bank Armenia',
  ],
  AB: [
    'Амра-банк',
    'Универсал-банк',
    'Абхазский народный банк',
    'Сбербанк Абхазии',
  ],
  MD: [
    'MAIB',
    'Moldindconbank',
    'Victoriabank',
    'OTP Bank',
    'Energbank',
    'Eximbank',
    'Comertbank',
    'Mobiasbanca',
    'ProCredit Bank',
    'EuroCreditBank',
  ],
  LA: [
    'BCEL',
    'Lao-Viet Bank',
    'Joint Development Bank',
    'Phongsavanh Bank',
    'Banque Franco-Lao',
    'ST Bank',
    'Lao China Bank',
  ],
};

export const POPULAR_FOREIGN_SBP_BANKS: Record<
  ForeignSbpCountryId,
  readonly string[]
> = {
  BY: ['Беларусбанк', 'Приорбанк', 'Белагропромбанк', 'БПС-Сбербанк'],
  KZ: ['Kaspi Bank', 'Народный Банк Казахстана', 'Bereke Bank', 'ForteBank'],
  UZ: ['Kapitalbank', 'Hamkorbank', 'Ipoteka Bank', 'Agrobank'],
  KG: ['MBank', 'Optima Bank', 'Bakai Bank', 'Demir Bank'],
  TJ: ['Амонатбонк', 'Эсхата Банк', 'Ориёнбонк', 'Алиф Банк'],
  AM: ['Ameriabank', 'Ardshinbank', 'ACBA Bank', 'Inecobank'],
  AB: ['Амра-банк', 'Универсал-банк', 'Абхазский народный банк'],
  MD: ['MAIB', 'Moldindconbank', 'Victoriabank', 'OTP Bank'],
  LA: ['BCEL', 'Lao-Viet Bank', 'Joint Development Bank'],
};

/** Подсказки поиска для зарубежных банков. */
export const FOREIGN_BANK_QUERY_ALIASES: Record<string, string> = {
  каспи: 'kaspibank',
  kaspi: 'kaspibank',
  халык: 'народныйбанкказахстана',
  halyk: 'народныйбанкказахстана',
  беларус: 'беларусбанк',
  приор: 'приорбанк',
  mbank: 'mbank',
  мбанк: 'mbank',
  амонат: 'амонатбонк',
  эсхата: 'эсхатабанк',
  maib: 'maib',
  bcel: 'bcel',
};
