// lib/achievements/config.ts
import { AchievementRarity, AchievementType } from '@prisma/client';
import { Achievement } from './types';

export const DEFAULT_ACHIEVEMENTS: Omit<Achievement, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // === ЗАЯВКИ ===
  {
    name: 'Первые шаги',
    description: 'Создайте свою первую заявку',
    icon: 'FileText',
    rarity: AchievementRarity.COMMON,
    type: AchievementType.APPLICATIONS,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Помощник',
    description: 'Создайте 5 заявок',
    icon: 'Users',
    rarity: AchievementRarity.RARE,
    type: 'APPLICATIONS',
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Активный участник',
    description: 'Создайте 10 заявок',
    icon: 'Star',
    rarity: AchievementRarity.EPIC,
    type: 'APPLICATIONS',
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Одобренная заявка',
    description: 'Получите одобрение первой заявки',
    icon: 'CheckCircle',
    rarity: AchievementRarity.RARE,
    type: 'APPLICATIONS',
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },

  // === ИГРЫ ===
  {
    name: 'Первый рекорд',
    description: 'Установите рекорд в любой игре',
    icon: 'Gamepad2',
    rarity: 'COMMON',
    type: AchievementType.GAMES,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Мастер полёта',
    description: 'Наберите 100+ очков в Leaf Flight',
    icon: 'Zap',
    rarity: AchievementRarity.RARE,
    type: AchievementType.GAMES,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Чемпион башни',
    description: 'Постройте башню высотой 15+ блоков',
    icon: 'Building2',
    rarity: AchievementRarity.EPIC,
    type: AchievementType.GAMES,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Игроман',
    description: 'Сыграйте в игры 50 раз',
    icon: 'Target',
    rarity: AchievementRarity.LEGENDARY,
    type: AchievementType.GAMES,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },

  // === СОЦИАЛЬНЫЕ ===
  {
    name: 'Первый друг',
    description: 'Добавьте первого друга',
    icon: 'Heart',
    rarity: 'COMMON',
    type: AchievementType.SOCIAL,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Социальная бабочка',
    description: 'Добавьте 10 друзей',
    icon: 'Users',
    rarity: AchievementRarity.RARE,
    type: AchievementType.SOCIAL,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Сердце сообщества',
    description: 'Поставьте 50 лайков историям',
    icon: 'Heart',
    rarity: AchievementRarity.EPIC,
    type: AchievementType.SOCIAL,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },

  // === СЕРИИ ===
  {
    name: 'Начало пути',
    description: 'Входите на сайт 3 дня подряд',
    icon: 'Flame',
    rarity: 'COMMON',
    type: AchievementType.STREAK,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Привычка',
    description: 'Входите на сайт 7 дней подряд',
    icon: 'Flame',
    rarity: AchievementRarity.RARE,
    type: AchievementType.STREAK,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Преданность',
    description: 'Входите на сайт 30 дней подряд',
    icon: 'Flame',
    rarity: AchievementRarity.LEGENDARY,
    type: AchievementType.STREAK,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },

  // === СООБЩЕСТВО ===
  {
    name: 'Помощник сообщества',
    description: 'Помогите 5 людям (лайкните их истории)',
    icon: 'Heart',
    rarity: AchievementRarity.RARE,
    type: AchievementType.COMMUNITY,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Ангел-хранитель',
    description: 'Помогите 25 людям',
    icon: 'Shield',
    rarity: AchievementRarity.EPIC,
    type: AchievementType.COMMUNITY,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Герой сообщества',
    description: 'Помогите 100 людям',
    icon: 'Star',
    rarity: AchievementRarity.LEGENDARY,
    type: AchievementType.COMMUNITY,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },

  // === ТВОРЧЕСТВО ===
  {
    name: 'Рассказчик',
    description: 'Напишите историю длиннее 100 слов',
    icon: 'FileText',
    rarity: 'COMMON',
    type: AchievementType.CREATIVITY,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Мастер слова',
    description: 'Напишите историю длиннее 500 слов',
    icon: 'Edit3',
    rarity: AchievementRarity.RARE,
    type: AchievementType.CREATIVITY,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Вдохновение',
    description: 'Ваша история получила 10+ лайков',
    icon: 'Star',
    rarity: AchievementRarity.EPIC,
    type: AchievementType.CREATIVITY,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },

  // === ОСОБЫЕ ===
  {
    name: 'Первопроходец',
    description: 'Стали одним из первых 100 пользователей',
    icon: 'Rocket',
    rarity: AchievementRarity.EXCLUSIVE,
    type: AchievementType.SPECIAL,
    isExclusive: true,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Легенда',
    description: 'Получите все остальные достижения',
    icon: 'Crown',
    rarity: AchievementRarity.EXCLUSIVE,
    type: AchievementType.SPECIAL,
    isExclusive: true,
    maxCount: 1,
    isActive: true,
  },
  {
    name: 'Благодарность',
    description: 'Получили помощь от сообщества',
    icon: 'Heart',
    rarity: AchievementRarity.RARE,
    type: AchievementType.SPECIAL,
    isExclusive: false,
    maxCount: 1,
    isActive: true,
  },
];

// Достижения для специальных событий
export const EVENT_ACHIEVEMENTS: Omit<Achievement, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Новогодний герой',
    description: 'Активны в новогодние праздники',
    icon: 'Snowflake',
    rarity: AchievementRarity.LEGENDARY,
    type: AchievementType.SPECIAL,
    isExclusive: true,
    maxCount: 1,
    isActive: true,
    validFrom: new Date('2024-12-31'),
    validTo: new Date('2025-01-07'),
  },
  {
    name: 'Весенний цветок',
    description: 'Присоединились весной 2024',
    icon: 'Flower',
    rarity: AchievementRarity.EPIC,
    type: AchievementType.SPECIAL,
    isExclusive: true,
    maxCount: 1,
    isActive: true,
    validFrom: new Date('2024-03-01'),
    validTo: new Date('2024-05-31'),
  },
];

// Все достижения
export const ALL_ACHIEVEMENTS = [
  ...DEFAULT_ACHIEVEMENTS,
  ...EVENT_ACHIEVEMENTS,
];
